---
title: "Simple document"
output: github_document
---


```{r, echo = FALSE,message=FALSE}
library(tidyverse)
library(readxl)
```

## Import some data

I want to import 'FAS_litters.csv'


```{r}
litters_df = read.csv("data/FAS_litters.csv")


```

Yay! I imported the dataset. Now I want better names.

```{r}
names(litters_df)

#clean_names is a func inside janitor func
#janitor::clean_names use this func without loading the entire package
litters_df = janitor::clean_names(litters_df)
```

Yay! Now I have better names.Let's look at the dataset.

```{r}

litters_df

#print out the first few rows
head(litters_df)
#print out the last few rows
tail(litters_df)

```

One I use a lot is:
```{r}
view(litters_df)
```


Here's 'skimr':
```{r}
skimr::skim(litters_df)
```

## Arguments in 'read_csv'

```{r, eval=FALSE}
litters_df = 
  read_csv(
  "data/FAS_litters.csv",
  skip = 5,
  col_names = FALSE,
  na = "low8")
```

## Parsing columns

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)

```


## Reading from excel

```{r}
mlb11_df = read_excel("data/mlb11.xlsx")
```

